image: php:8.1

services:
  - mysql:5.7

variables:
  MYSQL_ROOT_PASSWORD: secret
  MYSQL_DATABASE: laravel
  MYSQL_USER: laravel
  MYSQL_PASSWORD: secret
  DB_HOST: mysql
  DB_USERNAME: laravel
  DB_PASSWORD: secret
  DB_DATABASE: laravel
  SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY

cache:
  paths:
    - vendor/
    - node_modules/

stages:
  - test
  - deploy

phpunit:
  stage: test
  script:
    - php artisan test

deploy:
  stage: deploy
  script:
    - echo "====== 1. Deploying ======"
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | sudo tee /root/.ssh/id_rsa > /dev/null
    - sudo chmod 600 /root/.ssh/id_rsa
    - ssh-keyscan -H 162.43.25.155 >> ~/.ssh/known_hosts
    - ssh root@162.43.25.155 "cd /var/www/html/public_html/sankei-workflow-management && git pull origin main && composer install && php artisan migrate --force && php artisan config:cache && php artisan route:cache"
    - echo "====== Deploy success 🎉 🎉 🎉 ======"
  only:
    - main
  dependencies:
    - phpunit